# These are supported funding model platforms

github:
patreon: patreon.com/user?u=90375585
open_collective: # still waiting

custom: https://bmc.link/kinsleyKAJIVA
paypal: https://www.paypal.me/kinsleyKAJIVA
