# These are supported funding model platforms

github: kinsleykajiva
open_collective: # still waiting
Bitcoin: bitcoin:1JqfpzEuV2eehrKVGZtpcTSDDfJDWsuyKv
custom: https://www.paypal.me/kinsleyKAJIVA


